apiVersion: v1
kind: Namespace
metadata:
  name: qotd-svc-ocp
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-pdf
  namespace: qotd-svc-ocp
  labels:
    app: qotd
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-pdf
  template:
    metadata:
      labels:
        app: qotd-pdf
    spec:
      restartPolicy: Always
      containers:
        - name: qotd-pdf
          image: registry.gitlab.com/quote-of-the-day/qotd-pdf-service/v4.0.0:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3005
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENABLE_INSTANA
              value: "false"
            - name: ANOMALY_GENERATOR_URL
              value: "qotd-usecase.qotd-load.svc.cluster.local:3012"
            - name: QUOTE_SVC
              value: "qotd-quote:3001"
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "25m"
              memory: "300Mi"
            limits:
              cpu: "200m"
              memory: "800Mi"
      # nodeSelector:
      #   ocpnode: qotd-svc-ocp
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-pdf
  namespace: qotd-svc-ocp
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
      name: http
  selector:
    app: qotd-pdf