# permissions for end users to view operators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: operator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cl-operator
    app.kubernetes.io/part-of: cl-operator
    app.kubernetes.io/managed-by: kustomize
  name: cl-operator-operator-viewer-role
  namespace: clusterlink-operator
rules:
- apiGroups:
  - clusterlink.net
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterlink.net
  resources:
  - instances/status
  verbs:
  - get
