apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cl-operator
    app.kubernetes.io/part-of: cl-operator
  name: cl-operator-controller-manager
  namespace: clusterlink-operator
