##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage2
  labels:
    app: productpage2
    service: productpage2
spec:
  ports:
  - port: 9080
    #targetPort: 9080
    nodePort: 30002
    #protocol: TCP
    name: http
  selector:
    app: productpage2
  #type: LoadBalancer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage2-v1
  labels:
    app: productpage2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage2
  template:
    metadata:
      labels:
        app: productpage2
        version: v1
    spec:
      containers:
      - name: productpage2
        image: docker.io/istio/examples-bookinfo-productpage-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
