apiVersion: clusterlink.net/v1alpha1
kind: AccessPolicy
metadata:
  name: deny-private-workloads-connecting-to-metering-service-on-port-5051-on-prod
spec:
  privileged: true
  action: deny
  from:
  - workloadSelector:
      matchLabels:
        classification: private
        environment: prod
  to:
  - workloadSelector:
      matchLabels:
        workloadName: global-metering-service
        environment: prod
---
apiVersion: clusterlink.net/v1alpha1
kind: AccessPolicy
metadata:
  name: allow-connecting-to-metering-service-on-port-5051
spec:
  privileged: true
  action: allow
  from:
  - workloadSelector: {}
  to:
  - workloadSelector:
      matchLabels:
        workloadName: global-metering-service
        environment: prod
---
apiVersion: clusterlink.net/v1alpha1
kind: AccessPolicy
metadata:
  name: deny-connecting-to-metering-service-on-some-ports
spec:
  action: deny
  from:
  - workloadSelector: {}
  to:
  - workloadSelector:
      matchLabels:
        workloadName: global-metering-service
---
apiVersion: clusterlink.net/v1alpha1
kind: AccessPolicy
metadata:
  name: allow-connecting-to-named_workloads
spec:
  action: allow
  from:
  - workloadSelector: {}
  to:
  - workloadSelector:
      matchExpressions:
      - key: workloadName
        operator: Exists 
