apiVersion: clusterlink.net/v1alpha1
kind: PrivilegedAccessPolicy
metadata:
    name: deny-from-server1
spec:
    action: deny
    from: [{
            workloadSelector: {}
        }
    ]
    to:
        [{
            workloadSelector: {
                matchLabels: {
                    peer.clusterlink.net/name: server1
                }
            }
        }
    ]

