apiVersion: clusterlink.net/v1alpha1
kind: PrivilegedAccessPolicy
metadata:
    name: deny-from-server1
spec:
    action: deny
    from: [{
            workloadSelector: {}
        }
    ]
    to:
        [{
            workloadSelector: {
                matchLabels: {
                    clusterlink/metadata.gatewayName: server1
                }
            }
        }
    ]

